version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: site
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 18pohage
    ports:
      - "5432:5432"
    networks:
      - network2

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.15
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - network2

  test-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/site
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 18pohage
      SPRING_ELASTICSEARCH_URI: elasticsearch:9200

    networks:
      - network2
    ports:
      - "8080:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy

networks:
  network2:
    driver: bridge